### ISSUE TITLE
connect ECONNREFUSED

### ISSUE THREAD

**Issue by Microclisma** [tylerrmit/homebridge-coviva-hager#3]
Hello, addon has been working fine for months. I am running it in a homebridge container to allow coviva to be controlled in Home assistant. Starting from today I keep getting [CovivaHagerPlatform] "connect ECONNREFUSED 213.183.18.84:443" error and no device show in homebridge anymore. Any hint?
Before this error appeared I found this line in the log:
Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
No idea why it showed up nor how to delete it.
Even after backup this line keeps showing

**Comment by ams158** [comment]
Same here, it has been working perfectly and today I found that the plugin is not working, found same CONNECTION REFUSED message to the same IP.
I think that it's an error is related with Hager service, if I tried to connect to Coviva app via Internet and it doesn't work, but yes if I'm connected to the same Wifi.
I see here a bug in here, the plugin should connect to Coviva directly, without connecting to Internet.
I hope that Hager fix this soon.
BR

**Comment by Microclisma** [comment]
Yeah you are right. I managed to connect to coviva cause my phone is on the same wifi. Trying to access through the internet and I see its status as unknown.

**Comment by tylerrmit** [comment]
Not much I can do about it at the moment -- hopefully it's some sort of outage at Hager/Coviva that will eventually go away.  I haven't seen this exact situation before.  I'm finding that Alexa currently can't control my devices either.  Even if Hager don't care about this third-party plugin, they hopefully want to restore services to the Alexa interface they DO officially support.

Usually, if I can control my devices with my phone still, restarting homebridge will fix a problem.  The plugin does try to reconnect if it detects that a connection is down, but doesn't always succeed.  I wish it would always reconnect successfully by itself, but there haven't been enough opportunities for me to get to the bottom of why it needs the restart.

Usually, if I can't control my devices with my phone, restarting the Coviva Hub (and then Homebridge after the two lights have come on) helps.

In this case, I can control things with my phone, but restarting the the hub or home bridge doesn't help.  I get the same connection refused message as you.

There is a WEBSITE where you are supposed to be able to control your devices.  Google "my coviva".  You would normally login with your same coviva hub ID + email + password as the app.  Currently it's telling me that my password is incorrect.  If the "my coviva" website isn't working for you (us) then there's no way the homebridge plugin can.

Yes it'd be nice to be able to connect directly from homebridge to the Coviva hub on the local network, but I have been unable to reverse-engineer a way to do that.  It's annoying to be dependent on the manufacturer's cloud service -- I've been burned by Belkin Wemo/NetCam before -- but since Coviva is using an open KNX protocol, hopefully I could change out the hub to a different manufacturer's one, if push came to shove.  I think there are other hubs out there for KNX that support HomeKit more explicitly, but whether they have to go through a different cloud service, I don't know.

Anyway, feel free to play with the "my coviva" website and Alexa (or Google Home)?  If you see any of those three things working and you still can't get your devices up and running with reboots of the hub and homebridge, please let me know

**Comment by tylerrmit** [comment]
If I go to  http://www.hager.com/enduser/ I can login with my username and password.  (No Hub ID) required.

It asks me to accept an EULA dated 2017, then hit "Update my account".  I do that.  It says "Thank you.  We have stored your agreement to the GToU!"

I hit the logo to go to the main end user page where I originally found the web interface (which I used as the basis for writing the plugin -- translated the javascript into python test programs and then into a Homebridge plugin.

The web page is full of SOAP errors.  The section about the web interface says:

```
coviva web access

Operate your coviva Smartbox via the WebApp

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://api.myhager.com/gw/KoalaBoxService/v1?wsdl' : failed to load external entity "https://api.myhager.com/gw/KoalaBoxService/v1?wsdl"
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://api.myhager.com/gw/KoalaBoxService/v1?wsdl' : failed to load external entity "https://api.myhager.com/gw/KoalaBoxService/v1?wsdl"
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://api.myhager.com/gw/KoalaBoxService/v1?wsdl' : failed to load external entity "https://api.myhager.com/gw/KoalaBoxService/v1?wsdl"
You have no coviva boxes linked to myHager at this moment
```

There are similar SOAP errors in other sections.

They have lots of problems.  It doesn't look like something that just affects my little unsupported homebridge plugin.  It's widespread enough that they have to fix it.

If you want to complain to them, don't mention the homebridge plugin, just say you went to the end user page and you're getting the SOAP errors and your Alexa won't work.

**Comment by tylerrmit** [comment]
This is still better than the time -- day 1 -- when I paid my electrician to install all the switches, we went to register everything its activate it, and found that Hager's registration service was down for a scheduled outage.  I guess they thought it was safe to bring registration service down overnight... from Europe's perspective.  Not a good look in business hours for Australia.

**Comment by tylerrmit** [comment]
It is still down.  I have attempted to lodge a software support ticket with the local Hager support team, including a screenshot of their Hager "end user" web interface having a fit of SOAP errors and an allegation that Alexa isn't working

**Comment by ams158** [comment]
Hi Tylerrmit, for me it’s working perfectly now, I had to restart my homebridge application to reconnect to Coviva, no problems right now. I’m from Europe, maybe in other locations the issue persists. 

Br

**Comment by tylerrmit** [comment]
Hi ams158, I've just checked and it's up and running for me now, too.  Website is still reporting the SOAP errors, not that I really care :-)

But someone, somewhere might be using the web interface, so hopefully they'll look into that eventually.
